# Configuración dinámica de baseURL según la rama
[params.environments]
  [params.environments.production]
    baseURL = "https://docs.bamboopayment.com/"
  [params.environments.develop]
    baseURL = "https://doc.bamboopayment.com/"

title = "Bamboo Payment Systems"

# Enable local search
offlineSearch = true

navbar_logo = true
enableRobotsTXT = true

theme = ["hugo-dynamic-tabs", "docsy"]
relativeURLs = true
uglyURLs = true
SourceRelativeLinksEval = true

enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
id = "UA-00000000-0"

[languages]
[languages.en]
title = "Bamboo Payment"
description = "Bamboo Payment documentation"
languageName ="English"
contentDir = "content/en"
weight = 2

[languages.es]
title = "Bamboo Payment"
description = "Documentación de Bamboo Payment"
languageName ="Español"
contentDir = "content/es"
weight = 1

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
copyright = "Bamboo Payment"
platformName= "Bamboo Payment"

[params.ui]
sidebar_menu_compact = false
breadcrumb_disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      	hardWraps = false
    	unsafe = true
    	xHTML = false
